### ISSUE TITLE
"unknown command wsserver" when trying to connect to websocket

### ISSUE THREAD

**Issue by matthewmodestino** [erjadi/kubecraftadmin#14]
Hey Eric! Thanks for this, its really cool!

What version of Bedrock are you working with?

I deployed bedrock to k8s using latest https://github.com/itzg/docker-minecraft-bedrock-server and am able to connect and have cheats enabled and my user is an operator, but when I try to run the connect command I get "unknown command wsserver, please check command exists and that you have permissions to access it"

kubecraftadmin pod is deployed and listening fine...

Found similar stories: https://bugs.mojang.com/browse/BDS-1206

Any chance you ran into this and are using a particular version of bedrock server?

**Comment by erjadi** [comment]
Hey Matthew, I have to admit I haven't tested it with any dedicated server. Would be interesting to see if it works with Realms. The only way I've run it so far is by creating a world locally. Not that this (should) still allow you to do multiplayer, something I haven't tested yet either but that could be fun 👍 

In the end if the server has no support for /wsserver or /connect commands, my project cannot work :(

**Comment by matthewmodestino** [comment]
Just to ensure I mimic your set up, when you say locally, what are you running on?

**Comment by matthewmodestino** [comment]
Ah, I progressed a bit further. I logged into my windows 10 minecraft client and created a world locally, with cheats enabled. 

It now allows me to use the connect command ( `conect 192.168.1.183:30123/ws`) and I am able to connect to the kubecradftadmin server, but I don't receive the kubecraftadmin splash...I just see that I connected and have been given diamond gear and tnt. 

I try to run the init command and the connection dumps:

```
kubectl -n minecraft logs -f kubecraftadmin-5577ff8f78-jdjgj 
Listening
Player has entered!
init
Player has disconnected
2020/10/09 12:12:36 http: panic serving 10.1.74.1:50679: runtime error: invalid memory address or nil pointer dereference
goroutine 61 [running]:
net/http.(*conn).serve.func1(0xc000140280)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x14607c0, 0x202f020)
	/usr/local/go/src/runtime/panic.go:975 +0x3e9
github.com/sandertv/mcwss.(*Player).Position.func1(0xc00029a040)
	/go/src/github.com/sandertv/mcwss/player.go:99 +0x2b
reflect.Value.call(0x13f2dc0, 0xc0000ce770, 0x13, 0x15e6cfb, 0x4, 0xc0006e97e8, 0x1, 0x1, 0xc00013c200, 0xc0002f4010, ...)
	/usr/local/go/src/reflect/value.go:475 +0x8c7
reflect.Value.Call(0x13f2dc0, 0xc0000ce770, 0x13, 0xc0006e97e8, 0x1, 0x1, 0x0, 0xc000342001, 0x34)
	/usr/local/go/src/reflect/value.go:336 +0xb9
github.com/sandertv/mcwss.(*Player).handleIncomingPacket(0xc00000a1e0, 0xc0002c4000, 0x24, 0xc000280c40, 0xf, 0x1, 0x13ba120, 0xc00012e200, 0x0, 0x0)
	/go/src/github.com/sandertv/mcwss/player.go:511 +0x3a5
github.com/sandertv/mcwss.(*Server).handleResponse(0xc0001562c0, 0x179f520, 0xc0000261c0, 0xc000294000)
	/go/src/github.com/sandertv/mcwss/server.go:153 +0x405
net/http.HandlerFunc.ServeHTTP(0xc0001f77e0, 0x179f520, 0xc0000261c0, 0xc000294000)
	/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0x204c540, 0x179f520, 0xc0000261c0, 0xc000294000)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0000260e0, 0x179f520, 0xc0000261c0, 0xc000294000)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000140280, 0x17a2020, 0xc0002da000)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c

```

will go back and see if I missed a step in deploying the kubecraftadmin container? any debug steps I can take?

I noticed in the youtube video you typed `/connect 10.0.0.1/kubecraftadmin` to connect, but that doesn't work, for me.

**Comment by erjadi** [comment]
Hi Matthew, sorry to hear you're having so many issues. Yes a couple of points:

- In the video I'm connecting to /kubecraftadmin, but that has been indeed changed to /ws
- My test setup is running kubecraftadmin in a docker under WSL2 on Win10
- The Kubernetes cluster is an AKS cluster running on Azure
- Minecraft runs locally on my laptop and connects to the WSL2 network through the bridge NIC

I am honestly not sure what is going wrong in your case, it does seem to be related to the Minecraft -> KubeCraftAdmin connection level. Could you try running it in plain Docker and see how that goes?

**Comment by matthewmodestino** [comment]
Thanks so much for the prompt replies! 

No worries, I went 0-100 real quick in trying this on my microk8s cluster (which is containerd based) so that may be some of the issue. 

I'll get my windows box set up with WSL and get docker rocking! 

I have an azure trial too! will see how it goes!

**Comment by matthewmodestino** [comment]
no luck, unfortunately!

Now running Windows 10 Pro, WSL2 Ubuntu, docker. AKS. 

kubecraftadmin ontainer comes up and is reachable, 

Create a world locally, use /connect 

I connect to the container over WSL IP but don't get a splash and init does the same crash above. 

Will grab the minecraft versions and such. will keep poking...

**Comment by erjadi** [comment]
Just to double check, did you turn on cheats in the world? I'm trying to understand what else could be the issue....

**Comment by matthewmodestino** [comment]
Here's a more a thourough rundown in case i missed something:

Minecraft 1.16.40 - signed in with my xbox account - are you signed in to a live account?

Ubuntu 20.04.1 LTS - I installed docker manually and ran:
```
docker run -p 8000:8000 -v /home/mattymo/.kube:/.kube -e namespaces=default,kube-system erjadi/kubecraftadmin
```
I missed the note on 4 namespace max the first time around, made sure to add this time....

```
NAMES
6945e4a3934d        erjadi/kubecraftadmin   "/app/main"         4 seconds ago       Up 3 seconds        0.0.0.0:8000->8000/tcp   elated_satoshi
```
container comes up fine...

```
docker logs -f 6945e4a3934d
Listening on port 8000
```

Anything I can do to exec into the container and check that its all good? Here's the docker inpect:

```
    {
        "Id": "6945e4a3934d0a11d29fc1d385e52a8d7fcf09f804088f6554c3509e6e78f37e",
        "Created": "2020-10-15T11:58:41.8286897Z",
        "Path": "/app/main",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 495,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-10-15T11:58:42.07885Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:d22605a56c64ce052374c33558941f50f4388451210d71d8b1f47bb9693afc7e",
        "ResolvConfPath": "/var/lib/docker/containers/6945e4a3934d0a11d29fc1d385e52a8d7fcf09f804088f6554c3509e6e78f37e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/6945e4a3934d0a11d29fc1d385e52a8d7fcf09f804088f6554c3509e6e78f37e/hostname",
        "HostsPath": "/var/lib/docker/containers/6945e4a3934d0a11d29fc1d385e52a8d7fcf09f804088f6554c3509e6e78f37e/hosts",
        "LogPath": "/var/lib/docker/containers/6945e4a3934d0a11d29fc1d385e52a8d7fcf09f804088f6554c3509e6e78f37e/6945e4a3934d0a11d29fc1d385e52a8d7fcf09f804088f6554c3509e6e78f37e-json.log",
        "Name": "/elated_satoshi",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/mattymo/.kube:/.kube"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/888871b66089c4abc5ded5e82b5f5733d8c4e611faf303c5ebf12deb74e61fed-init/diff:/var/lib/docker/overlay2/cdd8918ed192d99ebfd300a6c683629171ea2450501da1cabcc35826e0ca7d33/diff:/var/lib/docker/overlay2/a07c9c859542deecb9c4a65376cbf1e3ce8b78b6975545d8d9b7158b51b4983a/diff:/var/lib/docker/overlay2/916df636318a2ed82eb746fae1004a1d98bd16f54e54411582e551b21accefce/diff:/var/lib/docker/overlay2/b00b467c49305c6f9f3a85170c0236b4e6ac81171388c60c6eb662bf85b8b334/diff",
                "MergedDir": "/var/lib/docker/overlay2/888871b66089c4abc5ded5e82b5f5733d8c4e611faf303c5ebf12deb74e61fed/merged",
                "UpperDir": "/var/lib/docker/overlay2/888871b66089c4abc5ded5e82b5f5733d8c4e611faf303c5ebf12deb74e61fed/diff",
                "WorkDir": "/var/lib/docker/overlay2/888871b66089c4abc5ded5e82b5f5733d8c4e611faf303c5ebf12deb74e61fed/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/mattymo/.kube",
                "Destination": "/.kube",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "6945e4a3934d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "namespaces=default,kube-system",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/app/main"
            ],
            "Image": "erjadi/kubecraftadmin",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.azure.dev.image.build.buildnumber": "20201011.1",
                "com.azure.dev.image.build.builduri": "vstfs:///Build/Build/332",
                "com.azure.dev.image.build.definitionname": "erjadi.kubecraftadmin",
                "com.azure.dev.image.build.repository.name": "erjadi/kubecraftadmin",
                "com.azure.dev.image.build.repository.uri": "https://github.com/erjadi/kubecraftadmin",
                "com.azure.dev.image.build.sourcebranchname": "main",
                "com.azure.dev.image.build.sourceversion": "2fe9f37f91f8ed4f872f99b922fa86f3408d9449",
                "com.azure.dev.image.system.teamfoundationcollectionuri": "https://dev.azure.com/ericjadi/",
                "com.azure.dev.image.system.teamproject": "KubeCraftAdmin - Pipelines"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "de4c3983817b201d3aaa28353c2e32f82baf116fb16415af4d310bd117f3ec9c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8000"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/de4c3983817b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "e835b01c4e9e697778c21ad6f1efd6786e0f4f99af4b2a4745910ec2d8a8fb0f",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "9d5c51e8292415ce2c37367c351d79fc3cb6c82448d6eb4614098ea318567073",
                    "EndpointID": "e835b01c4e9e697778c21ad6f1efd6786e0f4f99af4b2a4745910ec2d8a8fb0f",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

Cheats are activated, create a new world in survival....connect to websocket ok

![image](https://user-images.githubusercontent.com/31549209/96120954-56a20a80-0ebd-11eb-8d51-d7d3e7000bb5.png)

**Comment by erjadi** [comment]
Closed stale issue
